<%
CONST currAMDID = 1
CONST currAUDID = 2
CONST currBWPID = 3
CONST currBRRID = 4
CONST currBTPID = 5
CONST currCADID = 6
CONST currCHYID = 7
CONST currDNKID = 8
CONST currEUDID = 9
CONST currHKDID = 10
CONST currINRID = 11
CONST currJPYID = 12
CONST currMLRID = 13
CONST currMCPID = 14
CONST currNZDID = 15
CONST currNWKID = 16
CONST currSGDID = 17
CONST currSARID = 18
CONST currSKWID = 19
CONST currSLRID = 20
CONST currSWKID = 21
CONST currSWFID = 22
CONST currTWDID = 23
CONST currVNBID = 24
CONST currTHBID = 25
CONST currUSDID = 26
CONST currRURID = 27

CONST currAMDPR = 39.16 'American Dollar
CONST currAUDPR = 29.6833 'Australian Dollar
CONST currBWPPR = 8.7489996 'Botswana Pula
CONST currBRRPR = 14.4529 'Brazilian Real
CONST currBTPPR = 73.237099 'British Pound
CONST currCADPR = 31.752199 'Canadian Dollar
CONST currCHYPR = 4.7314701 'Chinese Yuan
CONST currDNKPR = 6.87609 'Danish Krone
CONST currEUDPR = 51.150799 'Euro
CONST currHKDPR = 5.0256701 'Hong Kong Dollar
CONST currINRPR = 0.89754802 'Indian Rupee
CONST currJPYPR = 0.37320101 'Japanese Yen
CONST currMLRPR = 10.3053 'Malaysian Ringgit
CONST currMCPPR = 3.44718 'Mexican Peso
CONST currNZDPR = 27.235901 'New Zealand Dollar
CONST currNWKPR = 6.21874 'Norwegian Kroner
CONST currSGDPR = 23.7607 'Singapore Dollar
CONST currSARPR = 6.4233599 'South African Rand
CONST currSKWPR = .037259798 'South Korean Won
CONST currSLRPR = 0.39575499 'Sri Lanka Rupee
CONST currSWKPR = 5.6589599 'Swedish Krona
CONST currSWFPR = 33.021301 'Swiss Franc
CONST currTWDPR = 1.22375 'Taiwan Dollar
CONST currVNBPR =  0.020447001 'Venezuelan Bolivar
CONST currTHBPR = 1 'Thai Baht
CONST currUSDPR = 39.16 'American Dollar
CONST currRURPR = 1.516 'Russia Rubles

CONST currAMDTI = "American Dollar"
CONST currAUDTI = "Australian Dollar"
CONST currBWPTI = "Botswana Pula"
CONST currBRRTI = "Brazilian Real"
CONST currBTPTI = "British Pound"
CONST currCADTI = "Canadian Dollar"
CONST currCHYTI = "Chinese Yuan"
CONST currDNKTI = "Danish Krone"
CONST currEUDTI = "Euro"
CONST currHKDTI = "Hong Kong Dollar"
CONST currINRTI = "Indian Rupee"
CONST currJPYTI = "Japanese Yen"
CONST currMLRTI = "Malaysian Ringgit"
CONST currMCPTI = "Mexican Peso"
CONST currNZDTI = "New Zealand Dollar"
CONST currNWKTI = "Norwegian Kroner"
CONST currSGDTI = "Singapore Dollar"
CONST currSARTI = "South African Rand"
CONST currSKWTI = "South Korean Won"
CONST currSLRTI = "Sri Lanka Rupee"
CONST currSWKTI = "Swedish Krona"
CONST currSWFTI = "Swiss Franc"
CONST currTWDTI = "Taiwan Dollar"
CONST currVNBTI = "Venezuelan Bolivar"
CONST currTHBTI = "Thai Baht"
CONST currUSDTI = "American Dollar"
CONST currRURTI = "Russia Rubles"
%>